import { fileURLToPath } from 'node:url';
import type { NextConfig } from 'next';

// Pin the monorepo root so Next doesn't latch onto an unrelated lockfile higher
// up the filesystem (e.g. C:\Users\DELL\package-lock.json).
const monorepoRoot = fileURLToPath(new URL('../..', import.meta.url));

const config: NextConfig = {
  reactStrictMode: true,
  outputFileTracingRoot: monorepoRoot,
  transpilePackages: ['@souramail/ui', '@souramail/auth', '@souramail/db', '@souramail/core'],
  // typedRoutes needs `.next/types` generated by a build; CI runs `tsc --noEmit`
  // standalone (no prior build), so it can't see app routes and rejects every
  // internal <Link href>. Re-enable once typecheck runs after `next build`.
  typedRoutes: false,
};

export default config;
