import containerQueries from '@tailwindcss/container-queries';
import forms from '@tailwindcss/forms';
import type { Config } from 'tailwindcss';

/**
 * "Kinetic Infrastructure" design system — mirrors design/tokens/kinetic-infrastructure.md
 * and the tailwind.config embedded in design/mockups/*.html verbatim.
 */
const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d5dbd8',
        'tertiary-fixed': '#ffdad3',
        'error-container': '#ffdad6',
        primary: '#006b59',
        'secondary-fixed': '#beecde',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#00201a',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#234e44',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#005143',
        'inverse-surface': '#2b322f',
        'inverse-primary': '#5ddbbe',
        'surface-container': '#e9efeb',
        'surface-variant': '#dee4e0',
        'on-surface': '#171d1b',
        secondary: '#3b665b',
        'on-tertiary-fixed-variant': '#7d2c1b',
        surface: '#f5fbf7',
        'outline-variant': '#bccac4',
        'on-secondary-fixed': '#00201a',
        'on-background': '#171d1b',
        'surface-container-high': '#e3eae6',
        outline: '#6d7a75',
        'inverse-on-surface': '#ecf2ee',
        'on-tertiary-container': '#551003',
        tertiary: '#9b4330',
        'surface-container-low': '#eff5f1',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#3d0600',
        'tertiary-fixed-dim': '#ffb4a4',
        'surface-bright': '#f5fbf7',
        'secondary-fixed-dim': '#a2d0c2',
        'surface-container-highest': '#dee4e0',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#5ddbbe',
        error: '#ba1a1a',
        'primary-container': '#00a48a',
        'on-tertiary': '#ffffff',
        background: '#f5fbf7',
        'secondary-container': '#bbe9db',
        'on-secondary-container': '#406b5f',
        'surface-tint': '#006b59',
        'on-primary-container': '#003128',
        'tertiary-container': '#db745d',
        'primary-fixed': '#7cf8da',
        'on-surface-variant': '#3d4945',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        pill: '9999px',
      },
      spacing: {
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        '4xl': '96px',
        margin: '32px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-xl': ['var(--font-geist)', 'Geist', 'sans-serif'],
        'headline-lg': ['var(--font-geist)', 'Geist', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-geist)', 'Geist', 'sans-serif'],
        'headline-md': ['var(--font-geist)', 'Geist', 'sans-serif'],
        'label-md': ['var(--font-geist)', 'Geist', 'sans-serif'],
        'label-sm': ['var(--font-geist)', 'Geist', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'Geist Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-xl': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '500' }],
        mono: ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
